[build]
  publish = "/"
  
[[redirects]]
  from = "/api/*"
  to = "https://discobots-api.example.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200